export default {
  nodeEnv: 'test',
  isProduction: false,
  port: 3000,
  sessionSecret: 'test-secret',
  betterstackHeartbeatUrl: '',
  betterstackLogtailKey: 'test-key',
  logLevel: 'debug',
  pgDatabase: 'test-db',
  pgHost: 'localhost',
  pgPassword: 'test-password',
  pgPort: 5432,
  pgUser: 'test-user',
  intercomClientId: 'test-client-id',
  intercomClientSecret: 'test-client-secret',
  intercomCallbackUrl: '/auth/intercom/callback',
  intercomUrl: 'https://api.intercom.io',
  encryptionAlgorithm: 'aes-256-gcm',
  encryptionKey: 'test-encryption-key',
  retryAttempts: 3,
  retryFactor: 2,
  retryMinTimeout: 1000,
  retryMaxTimeout: 5000,
  retryRandomize: false,
  ipAllowlist: '',
};
