databaseType = "PostgreSql"
id = "4d6f3af4-0504-44c8-890d-4edb992bf872"
name = "database"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.snoozeplus-local]
url = "jdbc:postgresql://localhost:5432/postgres"
schemas = [ "public" ]
displayName = "local"

[environments.snoozeplus-dev]
url = "jdbc:postgresql://localhost:5432/snoozeplus-dev"
schemas = [ "public" ]
displayName = "dev"

[environments.snoozeplus-prod]
url = "jdbc:postgresql://localhost:5432/snoozeplus"
schemas = [ "public" ]
displayName = "prod"
