#########################################################################################
##  WORKFLOW NAME
#########################################################################################
name: Create and Publish a Container Image

#########################################################################################
##  WORKFLOW TRIGGER
#########################################################################################
on:
  workflow_dispatch:

#########################################################################################
##  WORKFLOW CONCURRENCY
#########################################################################################
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#########################################################################################
##  WORKFLOW ENVIRONMENT VARIABLES
#########################################################################################
env:
  GITUB_REGISTRY: ghcr.io
  AZURE_REGISTRY: pixelcovetech.azurecr.io
  IMAGE_NAME: ${{ github.repository }}

#########################################################################################
##  WORKFLOW JOBS
#########################################################################################
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets `GITHUB_TOKEN` permissions for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Extract metadata (tags, labels) for ACR
        id: meta-acr
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.AZURE_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push-acr
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta-acr.outputs.tags }}
          labels: ${{ steps.meta-acr.outputs.labels }}
