#########################################################################################
##  WORKFLOW NAME
#########################################################################################
name: Deploy Container to Azure Web App

#########################################################################################
##  WORKFLOW TRIGGER
#########################################################################################
on:
  workflow_dispatch:

#########################################################################################
##  WORKFLOW CONCURRENCY
#########################################################################################
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#########################################################################################
##  WORKFLOW ENVIRONMENT VARIABLES
#########################################################################################
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

#########################################################################################
##  WORKFLOW JOBS
#########################################################################################
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SnoozePlus'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e7bfac84ef454b77be98ccbe243f18e5 }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
