name: Trigger auto deployment for snoozeplus

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/snoozeplus-AutoDeployTrigger-37a09839-68be-4674-959c-74cf70127168.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SNOOZEPLUS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SNOOZEPLUS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SNOOZEPLUS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: pixelcovetech.azurecr.io
          registryUsername: ${{ secrets.SNOOZEPLUS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SNOOZEPLUS_REGISTRY_PASSWORD }}
          containerAppName: snoozeplus
          resourceGroup: snoozeplus-intercom-integration
          imageToBuild: pixelcovetech.azurecr.io/snoozeplus:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


